image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - yarn global add windows-build-tools
  - resetvars.bat
  - yarn install --network-timeout 1000000 

build_script:
  - yarn release --win

test: off